version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  

    steps:
      - checkout  
      - run:
          name: Set up dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Run Unit Tests
          command: python -m unittest discover

workflows:
  version: 2
  test:
    jobs:
      - build
